[package]
name = "rocket-rest-api-demo"
version = "0.1.0"
edition = "2021"
description = "A demo REST API written in Rocket."
license = "MIT"

[dependencies]
serde = "1.0.152"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]